#!/usr/bin/env python3
"""
.scaffold/generators/gen_shader.py
Generates Vulkan compute shaders from a specification.

Usage:
    python gen_shader.py --name my_compute --buffers 2 --workgroup 256
    python gen_shader.py --name fft_pass --buffers 1 --workgroup 512 --push-constants "uint n, uint stage"

Outputs GLSL compute shader (.comp) ready for SPIR-V compilation.
"""

import argparse
from pathlib import Path
from textwrap import dedent


def generate_shader(name: str, n_buffers: int = 2, workgroup_x: int = 256,
                    push_constants: str = "", output: str = None) -> str:
    """Generate a GLSL compute shader."""

    # Buffer bindings
    buffer_decls = []
    for i in range(n_buffers):
        label = "Input" if i == 0 else "Output" if i == n_buffers - 1 else f"Buffer{i}"
        buffer_decls.append(dedent(f"""\
            layout(set = 0, binding = {i}) buffer {label}Buffer {{
                float data[];
            }} {label.lower()}_buf;"""))

    buffers_str = "\n\n".join(buffer_decls)

    # Push constants
    push_str = ""
    if push_constants:
        push_str = dedent(f"""
            layout(push_constant) uniform PushConstants {{
                {push_constants};
            }} params;
        """)

    shader = dedent(f"""\
        /**
         * {name}.comp
         * Generated by .scaffold/generators/gen_shader.py
         *
         * Compile: glslangValidator -V {name}.comp -o {name}.spv
         */

        #version 450

        layout(local_size_x = {workgroup_x}, local_size_y = 1, local_size_z = 1) in;

        // ─── Buffer Bindings ─────────────────────────────────────────────

        {buffers_str}
        {push_str}
        // ─── Main ───────────────────────────────────────────────────────

        void main() {{
            uint idx = gl_GlobalInvocationID.x;

            // TODO: Add bounds check
            // if (idx >= params.n) return;

            // TODO: Implement compute logic
            float value = input_buf.data[idx];
            output_buf.data[idx] = value;
        }}
    """)

    return shader


def main():
    parser = argparse.ArgumentParser(description="Generate a Vulkan compute shader")
    parser.add_argument("--name", required=True, help="Shader name")
    parser.add_argument("--buffers", type=int, default=2, help="Number of storage buffers")
    parser.add_argument("--workgroup", type=int, default=256, help="Workgroup size (X)")
    parser.add_argument("--push-constants", default="", help="Push constant fields")
    parser.add_argument("--output", default=None, help="Output file path")
    args = parser.parse_args()

    code = generate_shader(args.name, args.buffers, args.workgroup, args.push_constants)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code)
        print(f"Shader generated: {output_path}")
    else:
        print(code)


if __name__ == "__main__":
    main()
