#!/usr/bin/env python3
"""
.scaffold/generators/gen_model.py
Generates a PyTorch model file from a specification.

Usage:
    python gen_model.py --name MyModel --base transformer --output models/my_model.py
    python gen_model.py --name Detector --base cnn --num-classes 20

Reads ml/models/ for base architectures and generates a customized subclass.
"""

import argparse
import sys
from pathlib import Path
from textwrap import dedent

SCAFFOLD_DIR = Path(__file__).parent.parent
MODELS_DIR = SCAFFOLD_DIR / "ml" / "models"

BASE_TEMPLATES = {
    "base": "ScaffoldModel",
    "classifier": "Classifier",
    "transformer": "Transformer",
    "cnn": "CNN",
}


def generate_model(name: str, base: str, num_classes: int = 10,
                   d_model: int = 512, n_layers: int = 6) -> str:
    """Generate model source code."""

    if base not in BASE_TEMPLATES:
        print(f"Unknown base: {base}. Available: {', '.join(BASE_TEMPLATES)}")
        sys.exit(1)

    base_class = BASE_TEMPLATES[base]

    imports = f"from scaffold.ml.models import {base_class}"

    if base == "classifier":
        body = dedent(f'''
            class {name}({base_class}):
                """Generated classifier: {name}"""

                def __init__(self, input_dim, num_classes={num_classes}, **kwargs):
                    super().__init__(input_dim, num_classes, **kwargs)
        ''')
    elif base == "transformer":
        body = dedent(f'''
            class {name}({base_class}):
                """Generated transformer: {name}"""

                def __init__(self, vocab_size, num_classes={num_classes},
                             d_model={d_model}, n_layers={n_layers}, **kwargs):
                    super().__init__(d_model=d_model, n_layers=n_layers,
                                     vocab_size=vocab_size, **kwargs)
                    self.output_head = nn.Linear(d_model, num_classes)

                def forward(self, x):
                    features = super().forward(x)
                    # Use [CLS] token or mean pooling
                    pooled = features.mean(dim=1)
                    return self.output_head(pooled)
        ''')
        imports += "\nimport torch.nn as nn"
    elif base == "cnn":
        body = dedent(f'''
            class {name}({base_class}):
                """Generated CNN: {name}"""

                def __init__(self, in_channels=3, num_classes={num_classes}, **kwargs):
                    super().__init__(in_channels, num_classes, **kwargs)
        ''')
    else:
        body = dedent(f'''
            class {name}({base_class}):
                """Generated model: {name}"""

                def __init__(self):
                    super().__init__()
                    # Add layers here

                def forward(self, x):
                    # Implement forward pass
                    raise NotImplementedError
        ''')

    return f'"""\nGenerated by .scaffold/generators/gen_model.py\nBase: {base} ({base_class})\n"""\n\n{imports}\n\n{body}'


def main():
    parser = argparse.ArgumentParser(description="Generate a PyTorch model")
    parser.add_argument("--name", required=True, help="Model class name")
    parser.add_argument("--base", default="base", choices=BASE_TEMPLATES.keys(),
                        help="Base architecture")
    parser.add_argument("--output", default=None, help="Output file path")
    parser.add_argument("--num-classes", type=int, default=10)
    parser.add_argument("--d-model", type=int, default=512)
    parser.add_argument("--n-layers", type=int, default=6)
    args = parser.parse_args()

    code = generate_model(args.name, args.base, args.num_classes,
                          args.d_model, args.n_layers)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code)
        print(f"Model generated: {output_path}")
    else:
        print(code)


if __name__ == "__main__":
    main()
