#!/usr/bin/env bash
# .scaffold/hooks/on_generate.sh
# Runs after a file is generated by any generator.
#
# Receives the generated file path as $1.
# Use this to auto-format, validate, or log generated files.

set -euo pipefail

FILE="${1:?on_generate.sh requires a file path argument}"

echo "[scaffold] generated: $FILE"

# Auto-format based on extension
case "$FILE" in
    *.py)
        command -v black &>/dev/null && black --quiet "$FILE" 2>/dev/null || true
        command -v ruff &>/dev/null && ruff check --fix --quiet "$FILE" 2>/dev/null || true
        ;;
    *.js|*.ts)
        command -v prettier &>/dev/null && prettier --write "$FILE" 2>/dev/null || true
        ;;
    *.cpp|*.h)
        command -v clang-format &>/dev/null && clang-format -i "$FILE" 2>/dev/null || true
        ;;
    *.comp|*.vert|*.frag)
        # Validate GLSL shader
        command -v glslangValidator &>/dev/null && glslangValidator "$FILE" 2>/dev/null || true
        ;;
esac
