#!/usr/bin/env python3
"""
.scaffold/hooks/on_generate.py
Runs after a file is generated by any generator.

Receives the generated file path as the first argument.
Auto-formats based on file extension.
"""

import shutil
import subprocess
import sys


def _run_if_available(cmd, args):
    """Run a formatter if it's installed, silently skip otherwise."""
    if shutil.which(cmd):
        try:
            subprocess.run([cmd] + args, capture_output=True, timeout=30)
        except Exception:
            pass


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <file>", file=sys.stderr)
        sys.exit(1)

    filepath = sys.argv[1]
    print(f"[scaffold] generated: {filepath}")

    if filepath.endswith(".py"):
        _run_if_available("black", ["--quiet", filepath])
        _run_if_available("ruff", ["check", "--fix", "--quiet", filepath])
    elif filepath.endswith((".js", ".ts")):
        _run_if_available("prettier", ["--write", filepath])
    elif filepath.endswith((".cpp", ".h")):
        _run_if_available("clang-format", ["-i", filepath])
    elif filepath.endswith((".comp", ".vert", ".frag")):
        _run_if_available("glslangValidator", [filepath])


if __name__ == "__main__":
    main()
